services:
  - type: web
    name: terry-music
    runtime: docker
    region: singapore
    envVars:
      - key: MINIMAX_API_TOKEN
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
